"""workspace gen_defaults

Revision ID: f8574f9bcd51
Revises: 11567dda384e
Create Date: 2026-06-30 23:04:32.830792
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8574f9bcd51'
down_revision: Union[str, None] = '11567dda384e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('gen_defaults', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'gen_defaults')
    # ### end Alembic commands ###
