"""tiktok_accounts

Revision ID: 11567dda384e
Revises: a498bee9d174
Create Date: 2026-06-30 16:23:39.533394
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11567dda384e'
down_revision: Union[str, None] = 'a498bee9d174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiktok_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('open_id', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'open_id', name='uq_tiktok_ws_open')
    )
    op.create_index(op.f('ix_tiktok_accounts_workspace_id'), 'tiktok_accounts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiktok_accounts_workspace_id'), table_name='tiktok_accounts')
    op.drop_table('tiktok_accounts')
    # ### end Alembic commands ###
