"""provider-agnostic subscription + billing

Revision ID: abccafd043d0
Revises: 63e0e3d5356a
Create Date: 2026-06-30 15:07:36.835610
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'abccafd043d0'
down_revision: Union[str, None] = '63e0e3d5356a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('provider', sa.String(length=40), nullable=False, server_default='manual'))
    op.add_column('subscriptions', sa.Column('external_customer_id', sa.String(length=120), nullable=True))
    op.add_column('subscriptions', sa.Column('external_subscription_id', sa.String(length=120), nullable=True))
    op.add_column('subscriptions', sa.Column('monthly_credits', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('subscriptions', sa.Column('current_period_start', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('last_grant_period', sa.String(length=7), nullable=True))
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'last_grant_period')
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'current_period_start')
    op.drop_column('subscriptions', 'monthly_credits')
    op.drop_column('subscriptions', 'external_subscription_id')
    op.drop_column('subscriptions', 'external_customer_id')
    op.drop_column('subscriptions', 'provider')
    # ### end Alembic commands ###
